services:
  convo-assist:
    image: convo-assist
    build: .
    volumes:
      - ./.env:/app/.env
      - convo-assist_db:/app/db
    restart: always

volumes:
  convo-assist_db:
    external: true
